services:
  ssop:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ISSUER=http://localhost:3000
      - NODE_ENV=production
      - DEBUG=""
      - COOKIE_SECRET=change-this-to-a-random-32-char-string
    volumes:
      - ./users.json:/app/users.json:ro
      - ./clients.json:/app/clients.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 